"""Compare two performance snapshots.

Snapshots are JSON files generated by `tools/run_perf.py` and stored under
`perf/results/`.

This tool prints a Markdown table showing per-experiment runtime changes and
a small summary of failures and newly added/removed experiments.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True, slots=True)
class Row:
    """One comparison row."""

    exp_id: str
    a_seconds: float | None
    b_seconds: float | None
    a_ok: bool
    b_ok: bool


def _repo_root() -> Path:
    """Resolve repository root based on this file's location."""
    return Path(__file__).resolve().parents[1]


def _load_snapshot(path: Path) -> dict[str, Any]:
    """Load a JSON snapshot.

    Args:
        path: Path to snapshot file.

    Returns:
        Parsed JSON as dict.
    """
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise TypeError(f"Snapshot at {path} is not a JSON object")
    return data


def _resolve_snapshot(ref: str, *, results_dir: Path) -> Path:
    """Resolve a snapshot reference.

    Args:
        ref: Either a label (without .json) or a path to a .json file.
        results_dir: Default snapshot directory.

    Returns:
        Path to snapshot file.

    Raises:
        FileNotFoundError: If the snapshot cannot be found.
    """
    p = Path(ref)
    if p.suffix == ".json":
        if p.is_file():
            return p
    else:
        candidate = results_dir / f"{ref}.json"
        if candidate.is_file():
            return candidate
    raise FileNotFoundError(f"Snapshot not found for reference: {ref}")


def _index_experiments(snapshot: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """Index experiments by exp_id."""
    exps = snapshot.get("experiments", [])
    idx: dict[str, dict[str, Any]] = {}
    for e in exps:
        exp_id = str(e.get("exp_id"))
        idx[exp_id] = e
    return idx


def _fmt_seconds(x: float | None) -> str:
    """Format seconds for Markdown table."""
    if x is None:
        return ""
    return f"{x:.6f}"


def _fmt_delta(a: float | None, b: float | None) -> str:
    """Format absolute delta."""
    if a is None or b is None:
        return ""
    return f"{(b - a):+.6f}"


def _fmt_pct(a: float | None, b: float | None) -> str:
    """Format percent delta."""
    if a is None or b is None or a == 0:
        return ""
    return f"{((b - a) / a) * 100:+.2f}%"


def main(argv: list[str] | None = None) -> int:
    """CLI entry point.

    Args:
        argv: Optional argv list.

    Returns:
        Exit code (0 on success).
    """
    p = argparse.ArgumentParser(description="Compare two perf snapshots.")
    p.add_argument("--a", required=True, help="Snapshot A label or path.")
    p.add_argument("--b", required=True, help="Snapshot B label or path.")
    p.add_argument("--results-dir", default="perf/results", help="Snapshot directory.")
    p.add_argument(
        "--only-changed",
        action="store_true",
        help="Show only experiments with changed runtime or status.",
    )
    args = p.parse_args(argv)

    repo_root = _repo_root()
    results_dir = repo_root / args.results_dir

    path_a = _resolve_snapshot(args.a, results_dir=results_dir)
    path_b = _resolve_snapshot(args.b, results_dir=results_dir)

    snap_a = _load_snapshot(path_a)
    snap_b = _load_snapshot(path_b)

    idx_a = _index_experiments(snap_a)
    idx_b = _index_experiments(snap_b)

    all_ids = sorted(set(idx_a) | set(idx_b))

    rows: list[Row] = []
    for exp_id in all_ids:
        ea = idx_a.get(exp_id)
        eb = idx_b.get(exp_id)
        a_seconds = float(ea["seconds"]) if ea and ea.get("seconds") is not None else None
        b_seconds = float(eb["seconds"]) if eb and eb.get("seconds") is not None else None
        a_ok = bool(ea and int(ea.get("returncode", 1)) == 0)
        b_ok = bool(eb and int(eb.get("returncode", 1)) == 0)

        if args.only_changed and a_seconds == b_seconds and a_ok == b_ok:
            continue

        rows.append(
            Row(exp_id=exp_id, a_seconds=a_seconds, b_seconds=b_seconds, a_ok=a_ok, b_ok=b_ok)
        )

    print("# Performance comparison")
    print()
    print(f"- A: `{path_a.name}`")
    print(f"- B: `{path_b.name}`")
    print()
    print("| Experiment | A (s) | B (s) | Δ (s) | Δ (%) | A ok | B ok |")
    print("|:--|--:|--:|--:|--:|:--:|:--:|")
    for r in rows:
        print(
            "| "
            + r.exp_id
            + " | "
            + _fmt_seconds(r.a_seconds)
            + " | "
            + _fmt_seconds(r.b_seconds)
            + " | "
            + _fmt_delta(r.a_seconds, r.b_seconds)
            + " | "
            + _fmt_pct(r.a_seconds, r.b_seconds)
            + " | "
            + ("✅" if r.a_ok else "❌")
            + " | "
            + ("✅" if r.b_ok else "❌")
            + " |"
        )

    added = [x for x in all_ids if x not in idx_a]
    removed = [x for x in all_ids if x not in idx_b]
    if added or removed:
        print()
    if added:
        print(f"**Added in B:** {', '.join(added)}")
    if removed:
        print(f"**Removed in B:** {', '.join(removed)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
